config/routes.rb
Rails.application.routes.draw do
  root 'csv_uploads#new'

  resources :csv_uploads, only: :create

  namespace :api do
    resources :users, only: :index
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :user_skills, dependent: :destroy
  has_many :users, through: :user_skills
  
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
require 'csv'

class User < ApplicationRecord
  has_many :user_skills, dependent: :destroy
  has_many :skills, through: :user_skills

  def self.import(path)
    CSV.foreach(path, headers: true) do |row|
      csv_values = row.to_hash
      user = User.create!(email: csv_values['email'],
                          name: csv_values['name'],
                          global_admin: (csv_values[:'global_admin'] == 't'),
                          timezone: csv_values['_timezone'],
                          receive_marketing: (csv_values['receive_marketing'] == 't'),
                          external_identifier: csv_values['external_id'])

      next unless csv_values['Skills'].present?
      
      csv_values['Skills'].split(',').each do |name|
        user.skills << Skill.find_or_create_by!(name: name.strip)
      end
     end
  end
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def index
    render json: User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/csv_uploads_controller.rb
class CsvUploadsController < ApplicationController
  def new
  end

  def create
    User.import(params[:file].path)
    render status: :created
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/csv_uploads/create.html.erb
<h1>CSV successfully uploaded!</h1>

app/views/csv_uploads/new.html.erb
<h1>Upload your CSV below</h1>
<%= form_tag csv_uploads_path, multipart: true do %>
  <label for="file">Upload Your CSV</label><%= file_field_tag :file %>
  <%= submit_tag 'Upload CSV' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UsersWithSkills</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>